version: '3.0'
services:
  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-mysql
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
